name: Recipes CI

on:
  push:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      
      - name: Show Files
        run: ls -la

      - name: Show Recipes
        run: ls -la Recipes